### ISSUE TITLE
Test problem

### ISSUE THREAD

**Issue by TG-MIO** [salehjg/DeepPoint-V2-FPGA#5]
I am using the Kerneltests you provided to test the module. But I can't see exactly how the test is done here, because KernelTestXXXX is an unviewable file. Is there any way to know the specific plan of the test?
![测试](https://github.com/salehjg/DeepPoint-V2-FPGA/assets/50563596/85b982ef-2c25-4a36-b75a-f400b15ffa6f)

**Comment by salehjg** [comment]
Hi there,

I am a bit confused about the question. KernelTests, for example [this one](https://github.com/salehjg/DeepPoint-V2-FPGA/blob/master/test/kerneltests/conv2/CMakeLists.txt), create a standalone binary for testing a specific HLS kernel directly, without involving the host program and OpenCL.

So, the executables should be built. Otherwise, the compilation fails somewhere. Without logs, I would be just guessing.

**Comment by TG-MIO** [comment]
Thank you for your answer, I did not find the code for testing before, now I do, thank you again! @salehjg

**Comment by salehjg** [comment]
I'll keep this issue open for a while. 
Please feel free to post any questions you might have, I'd be happy to help.
@TG-MIO

**Comment by salehjg** [comment]
I am closing this issue. Please let me know if I can be of any assistance. I would be more than happy to help.
